name: menosC-Compiler

services:
  build-env:
    image: alpine:latest
    volumes:
      - ./build:/build
    command: >
      sh -c "apk add --no-cache build-base &&
             touch /build/hello2 &&
             ls /build"

  final:
    image: alpine:latest
    depends_on:
      - build-env
    volumes:
      - ./build:/build
    command: >
      sh -c "ls /build"